### ISSUE TITLE
config overrides

### ISSUE THREAD

**Issue by larkinrobert** [tonycapone/serverless-ses-forwarder#1]
I'll work on this myself during the week, I could just be missing something, ran out of time this weekend.
The upstream code assumes the presence of a prefix ( emailKeyPrefix ), this key is not included in the config.yml for overriding.  Focused on this because no matter how permissive my policies are I always get an access denied error from copyObject().

**Comment by tonycapone** [comment]
Hi @larkinrobert. 

The emailKeyPrefix  is set to  '' in `handler.js`.  My reasoning for this at the time was simply to minimize complexity and due to the fact that fixed prefixes in S3 can affect performance due to how S3 does sharding. 

However I see how this is confusing and it probably makes more sense just to expose `emailKeyPrefix` as a config item in `config.yml` the same as the other configuration. Thoughts?

I'm not positive how the key prefix would affect permissions for the S3 bucket though. The policies created in `serverless.yml` should grant privileges to everything in the bucket. Let me know if you find out anything more about that.

**Comment by larkinrobert** [comment]
doh, sorry.  I think I was getting a permissions error because the path was actually wrong, as aws returns 403 in that case.
I tried using environment variables (without changing any code) without success...I think that would be the best way to go if possible.  I mean use env for everything that isn't an email address or domain.
I'm currently working out how I might do this with dynamodb as a data store for the email forwarding.  Never used dynamodb before and I'm not a dba, so I'm still just playing with it.
Thanks for doing this btw, really good step forward with this idea.
